FROM openjdk:8u191-jdk-alpine

LABEL maintainer="onsoim <onsoim@gmail.com>" 

COPY . /motizen

WORKDIR /motizen

# docker run --rm -it -v $(pwd):/apk motizen-sign sh Sign.sh old_unsigned.apk new_signed.apk