From python

LABEL maintainer="onsoim <onsoim@gmail.com>" 

RUN pip install \
	django

WORKDIR /application

# docker run --rm -it -v $(pwd):/application -p 80:8080 django python manage.py runserver 0.0.0.0:8080
